push

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -2,11 +2,14 @@
 
 echo "Running pre-commit checks..."
 
-result=$(stylua --config-path config/nvim/lua/.stylua.toml config/nvim/lua; echo $?)
+result=$(
+	stylua --config-path config/nvim/lua/.stylua.toml config/nvim/lua
+	echo $?
+)
 
 if [ $result -eq 0 ]; then
-  echo "Pre-commit passed, committing changes..."
+	echo "Pre-commit passed, committing changes..."
 else
-  echo "Pre-commit failed! Aborting commit."
-  exit 1 
+	echo "Pre-commit failed! Aborting commit."
+	exit 1
 fi
